---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - synthetic.clodevo.com
  resources:
  - configprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synthetic.clodevo.com
  resources:
  - configprobes/finalizers
  verbs:
  - update
- apiGroups:
  - synthetic.clodevo.com
  resources:
  - configprobes/status
  verbs:
  - get
  - patch
  - update
